baseURL = "https://example.org/"
locale = "en-US"
title = "Hugo Grid Gallery Example"
theme = "hugo-grid-gallery"
disableKinds = ["taxonomy", "term"]

[params.hugo-grid-gallery]
  debug = false
  teaserWordLimit = 18

[params.hugo-grid-gallery.recentlyUpdated]
  days = 3650
  limit = 2
  symbol = "⭐"
  title = "Recently Updated"
